### PR TITLE
Add support for macOS Catalina.

### LINKED ISSUE #4: Catalina Compatibility
I was able to use this library on Catalina, the only thing that is not compatible is `Styles` who landed in SwiftUI 2, besides that all works, maybe you can add @available safeguards

Thanks!

### PR DESCRIPTION
**Pull request by Sameesunkaria**
Closes #4

Changes from #5 are contained in here.

### CODE REVIEW

**Comment by Sameesunkaria** [comment]
@melMass Do these changes work for you?

**Comment by melMass** [comment]
> @melMass Do these changes work for you?

Yes, I just tested the `catalina-support` branch it does.

Thanks

**Comment by Sameesunkaria** [comment]
Great!

**Comment by melMass** [comment]
Are you sure it requires a separate branch?

**Comment by Sameesunkaria** [comment]
I also want to update the readme, and then I can merge the changes into `main`. Unfortunately, I had encountered memory related issues after my recent change related to adding a row separator therefore, I can't prepare a new release immediately. Until then you can target the `main` branch instead of the latest release.

**Comment by Sameesunkaria** [comment]
Thanks @melMass :)
The changes are in `main`.

**Pull request merged**
